--=====================================================================================
-- BLU - generated user custom sound manifest
-- Generated by tools\GenerateUserSoundManifest.ps1. Keep manual edits in user_sounds.lua.
--
-- This file ships with an empty manifest so BLU.xml always has a file to load
-- (previously gitignored, so every packaged release hit a load error). Running
-- the generator locally overwrites this file with your personal sound list —
-- do not commit personal entries back to the shared repo.
--=====================================================================================

BLU_UserCustomSoundManifest = {}
